# Generated by Django 5.0.6 on 2024-05-28 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Film Name')),
                ('is_paid', models.BooleanField(default=False)),
                ('price', models.FloatField()),
                ('type', models.CharField(max_length=100, verbose_name='Type')),
                ('language', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Marathi', 'Marathi')], max_length=100, verbose_name='Language')),
                ('country', models.CharField(choices=[('India', 'India'), ('America', 'America'), ('Korea', 'Korea')], max_length=100, verbose_name='Country')),
                ('time', models.CharField(max_length=100, verbose_name='Time')),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='image')),
                ('video', models.FileField(null=True, upload_to='videos/', verbose_name='video')),
            ],
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('duration', models.CharField(max_length=50, verbose_name='duration')),
                ('charges', models.IntegerField(verbose_name='charges')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fid', models.ForeignKey(db_column='fid', on_delete=django.db.models.deletion.CASCADE, to='filmapp.film')),
            ],
        ),
        migrations.CreateModel(
            name='FilmHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.ForeignKey(db_column='fid', on_delete=django.db.models.deletion.CASCADE, to='filmapp.film')),
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
