# Generated by Django 5.0.6 on 2024-05-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='views',
            field=models.BigIntegerField(default=0, verbose_name='views'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='film',
            name='type',
            field=models.CharField(choices=[('Movie', 'Movie'), ('Web-Series', 'Web-Series'), ('Drama', 'Drama')], max_length=100, verbose_name='Type'),
        ),
    ]
